name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}   # EC2 퍼블릭 IP
        username: ${{ secrets.EC2_USER }}   # EC2 유저 (ubuntu)
        key: ${{ secrets.EC2_SSH_KEY }}   # SSH 접속 키 (보안 Secret)
        script: |
          cd /home/ubuntu/counter-api
          git pull origin main
          npm install
          pm2 restart all
